/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.*;
import java.awt.*; 
import java.awt.event.*;
/**
 *
 * @author strangequark
 */
public class PayrollCardLayout extends javax.swing.JPanel {
    JPanel cards;
    final static String BUTTONPANEL = "Card with JButtons";
    final static String TEXTPANEL = "Card with JTextField";
    /**
     * Creates new form PayrollCardLayout
     */
    public PayrollCardLayout() {
        initComponents();
    }
    public void addComponentToPane(Container pane) {
        //Put the JComboBox in a JPanel to get a nicer look.
        PayrollNameSSNLookuppanel pynameslookup = new PayrollNameSSNLookuppanel(); //use FlowLayout

         
        //Create the "cards".
        PayrollNameSSNLookupResults pynamesresults = new PayrollNameSSNLookupResults();
         
        //JPanel card2 = new JPanel();
        //card2.add(new JTextField("TextField", 20));
         
        //Create the panel that contains the "cards".
        cards = new JPanel(new CardLayout());
        cards.add(pynameslookup, BUTTONPANEL);
        cards.add(pynamesresults, TEXTPANEL);
        pynameslookup.addCards(cards);
        pynameslookup.addPResults(pynamesresults);
        /*
        cards
        cards.add(card1, BUTTONPANEL);
        cards.add(card2, TEXTPANEL);
         */
        //pane.add(comboBoxPane, BorderLayout.PAGE_START);
        pane.add(cards, BorderLayout.CENTER);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
